### ISSUE TITLE
craft --install-deps nextcloud-client fails

### ISSUE THREAD

**Issue by mzed2k** [nextcloud/desktop-client-blueprints#12]
I've followed the instructions and installed Python3 and VS 19 Community, then at step 5 installing nextcloud-client dependencies fails with many errors:

PS C:\Craft64> craft --install-deps nextcloud-client
Craft               : C:\Craft64
Version             : master
ABI                 : windows-cl-msvc2019-x86_64
Download directory  : C:\Craft64\download
Cache repository    : https://files.kde.org/craft/Qt5/23.11/windows/cl/msvc2019/x86_64
'logs'
Traceback (most recent call last):
  File "C:\Craft64\craft\bin\craft.py", line 424, in <module>
    success = main(timer)
              ^^^^^^^^^^^
  File "C:\Craft64\craft\bin\craft.py", line 406, in main
    if not CraftCommands.run(package, action, tempArgs):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\CraftCommands.py", line 412, in run
    depList = depPackage.getDependencies(depType=depType)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 140, in getDependencies
    self.depenendencyType = depType
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 46, in depenendencyType
    self.__resolveDependencies()
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 61, in __resolveDependencies
    self.dependencies.extend(self.__readDependenciesForChildren([(x, None) for x in self.children.values()]))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 110, in __readDependenciesForChildren
    p.depenendencyType = self.depenendencyType
    ^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 46, in depenendencyType
    self.__resolveDependencies()
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 54, in __resolveDependencies
    self.dependencies.extend(self.__readDependenciesForChildren(subinfo.runtimeDependencies.items()))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 110, in __readDependenciesForChildren
    p.depenendencyType = self.depenendencyType
    ^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 46, in depenendencyType
    self.__resolveDependencies()
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 54, in __resolveDependencies
    self.dependencies.extend(self.__readDependenciesForChildren(subinfo.runtimeDependencies.items()))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 110, in __readDependenciesForChildren
    p.depenendencyType = self.depenendencyType
    ^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 46, in depenendencyType
    self.__resolveDependencies()
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 54, in __resolveDependencies
    self.dependencies.extend(self.__readDependenciesForChildren(subinfo.runtimeDependencies.items()))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 110, in __readDependenciesForChildren
    p.depenendencyType = self.depenendencyType
    ^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 46, in depenendencyType
    self.__resolveDependencies()
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 54, in __resolveDependencies
    self.dependencies.extend(self.__readDependenciesForChildren(subinfo.runtimeDependencies.items()))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 110, in __readDependenciesForChildren
    p.depenendencyType = self.depenendencyType
    ^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 46, in depenendencyType
    self.__resolveDependencies()
  File "C:\Craft64\craft\bin\Blueprints\CraftDependencyPackage.py", line 51, in __resolveDependencies
    subinfo = self.subinfo
              ^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Blueprints\CraftPackageObject.py", line 358, in subinfo
    return self.instance.subinfo
           ^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Blueprints\CraftPackageObject.py", line 333, in instance
    pack = self._Module.Package()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\etc\blueprints\locations\craft-blueprints-kde\libs\_msvc\libogg\libogg.py", line 18, in __init__
    BinaryPackageBase.__init__(self)
  File "C:\Craft64\craft\bin\Package\BinaryPackageBase.py", line 18, in __init__
    PackageBase.__init__(self)
  File "C:\Craft64\craft\bin\Package\PackageBase.py", line 34, in __init__
    CraftBase.__init__(self)
  File "C:\Craft64\craft\bin\CraftBase.py", line 41, in inner
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\CraftBase.py", line 60, in __init__
    self.subinfo = self.package._Module.subinfo(self)  # type: info.infoclass
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\info.py", line 85, in __init__
    self.setTargets()
  File "C:\Craft64\etc\blueprints\locations\craft-blueprints-kde\libs\_msvc\libogg\libogg.py", line 6, in setTargets
    self.addCachedAutotoolsBuild(f"libs/_autotools/{self.parent.package.name}")
  File "C:\Craft64\craft\bin\info.py", line 273, in addCachedAutotoolsBuild
    manifest = CraftManifest.CraftManifest.fromJson(json)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Utils\CraftManifest.py", line 184, in fromJson
    p = CraftManifestEntry.fromJson(package)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Utils\CraftManifest.py", line 108, in fromJson
    [CraftManifestBuild.fromJson(fileData) for fileData in data["build"]],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Utils\CraftManifest.py", line 75, in fromJson
    f = CraftManifestEntryFile.fromJson(v)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Utils\CraftManifest.py", line 36, in fromJson
    return CraftManifestEntryFile(FileType.fromString(data["fileType"]), data["fileName"], data["checksum"])
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Craft64\craft\bin\Utils\CraftManifest.py", line 25, in fromString
    return cls.__sting_map[name.lower()]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'logs'


Any suggestions?
Thanks,
Martin

**Comment by mgallien** [comment]
@mzed2k are you able to build other software ?
I mean that I am not sure I do get what is the error there
you may want to try some application from the kde blueprints repository

**Comment by mzed2k** [comment]
Thanks @mgallien, I'm no developer. I'v just followed the instructions to build the client, as it looked doable.
I've started from scratch, after many hours debugging the dependencies I'm able to start the build process. But it fails midway with errors I don't understand.
The desktop client trashes big file uploads. So I've forked it, changed some lines and then I've tried to get the build process working.
Now I give up...

**Comment by pawprintdigital** [comment]
I'm having the same issue here.

I've tried on both a Windows 10 environment (with Visual Studio 2019) and a Windows 11 environment (Visual Studio 2022).

```
Craft               : C:\Craft64
ABI                 : windows-cl-msvc2022-x86_64
Download directory  : C:\Craft64\download
Cache repository    : https://files.kde.org/craft/Qt6/24.04/windows/cl/msvc2022/x86_64
PS C:\Craft64> craft --install-deps nextcloud-client
Craft               : C:\Craft64
ABI                 : windows-cl-msvc2022-x86_64
Download directory  : C:\Craft64\download
Cache repository    : https://files.kde.org/craft/Qt6/24.04/windows/cl/msvc2022/x86_64
C:\Craft64\etc\blueprints\locations\desktop-client-blueprints\nextcloud-client\nextcloud-client.py failed:
Failed to load package C:\Craft64\etc\blueprints\locations\desktop-client-blueprints\nextcloud-client\nextcloud-client.py
PS C:\Craft64>
```

I've tried several times now to get a valid build environment running, both following the instructions on Windows from this repository and also following the official wiki and trying to compile on OpenSUSE, but nothing has worked.

Any help would be greatly appreciated!

Many thanks
Lee

**Comment by mgallien** [comment]
we do not maintain [Craft](https://community.kde.org/Craft)
we only maintain a [few blueprints](https://github.com/nextcloud/desktop-client-blueprints/)
as far as I can say, the current blueprints are working with current Craft
for generic issues with Craft I highly recommend reaching out to the KDE community that has always been nice in my experience

**Comment by mgallien** [comment]
> I'm having the same issue here.
> 
> I've tried on both a Windows 10 environment (with Visual Studio 2019) and a Windows 11 environment (Visual Studio 2022).
> 
> ```
> Craft               : C:\Craft64
> ABI                 : windows-cl-msvc2022-x86_64
> Download directory  : C:\Craft64\download
> Cache repository    : https://files.kde.org/craft/Qt6/24.04/windows/cl/msvc2022/x86_64
> PS C:\Craft64> craft --install-deps nextcloud-client
> Craft               : C:\Craft64
> ABI                 : windows-cl-msvc2022-x86_64
> Download directory  : C:\Craft64\download
> Cache repository    : https://files.kde.org/craft/Qt6/24.04/windows/cl/msvc2022/x86_64
> C:\Craft64\etc\blueprints\locations\desktop-client-blueprints\nextcloud-client\nextcloud-client.py failed:
> Failed to load package C:\Craft64\etc\blueprints\locations\desktop-client-blueprints\nextcloud-client\nextcloud-client.py
> PS C:\Craft64>
> ```
> 
> I've tried several times now to get a valid build environment running, both following the instructions on Windows from this repository and also following the official wiki and trying to compile on OpenSUSE, but nothing has worked.
> 
> Any help would be greatly appreciated!
> 
> Many thanks Lee

that issue has been solved for now
